# Access latex builds, not forced
[[redirects]]
  from = "/notater/*"
  to = "https://haved-notater.netlify.com/notater/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/algdat/*"
  to = "/algdat/index.html"
  status = 200

[[redirects]]
  from = "/algdat-eksamen/*"
  to = "/algdat-eksamen/index.html"
  status = 200

[build.processing]
  skip_processing = true

# All the following are from hugo example, but I removed split testing
[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.92.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.92.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.92.0"
