name = "Topbody"
license = "MIT"
licenselink = "https://github.com/haved/haved.no/blob/master/themes/topbody/LICENSE"
description = "A custom theme for my personal homepage"
homepage = "http://haved.no/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Håvard Krogstie"
  homepage = "haved"
